# Generated by Django 6.0.4 on 2026-07-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_transaction_mpesa_receipt_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
