# Generated by Django 6.0.4 on 2026-08-13 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='package',
            name='speed_limit',
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_description',
            field=models.CharField(default='Valid for continuous high-speed browsing.', help_text='e.g. Valid for 1 Hour of continuous high-speed browsing.', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide package from portal'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(help_text='e.g. 1 hour, 24 hours, Weekly', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Ksh, e.g. 10.00', max_digits=10),
        ),
    ]
